[functions]
  node_bundler = "esbuild"
  directory = "."
  external_node_modules = ["serverless-http"]
[[redirects]]
  force = false
  from = "/*"
  status = 200
  to = "/.netlify/functions/serverless-handler/:splat"

[build]
  publish = "public"
  command = "npm install serverless-http"
